<details>

<summary>Debug</summary>

Working directory
```{r}
getwd()
```

needs_preview()
```{r}
needs_preview
```

is_interactive()
```{r}
is_interactive
```

Knitr Output.dir
```{r}
knitr::opts_knit$get("output.dir")
```

Child mode
```{r}
knitr::opts_knit$get("child")
```

Viewer null
```{r}
is.null(getOption("viewer"))
```

In tmp dir
```{r}
!is.null(knitr::opts_knit$get("output.dir")) &&
  !identical(knitr::opts_knit$get("output.dir"), getwd())
```

knitr.in.progress
```{r}
getOption("knitr.in.progress")
```

rstudio.notebook.executing
```{r}
getOption("rstudio.notebook.executing")
```

TESTTHAT_interactive
```{r}
Sys.getenv("TESTTHAT_interactive")
```

TESTTHAT
```{r}
Sys.getenv("TESTTHAT")
```

interactive
```{r}
interactive()
```

objects in this environment
```{r}
ls()
```

<details>

<summary>knitr::opts_knit</summary>
```{r}
print(knitr::opts_knit$get())
```

</details>

<details>

<summary>knitr::opts_chunk</summary>
```{r}
print(knitr::opts_chunk$get())
```

</details>

<details>

<summary>Sys.getenv()</summary>
```{r}
print(Sys.getenv())
```

</details>

<details>

<summary>options()</summary>
```{r}
print(options())
```

</details>

</details>

